dist: trusty
sudo: required
os:
  - linux
  - osx
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./build.linux.bsh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then ./build.xcode.bsh; fi
script:
  # - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  # - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # - export CC=/usr/bin/gcc-6
  # - export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  - cd build
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then xcodebuild -configuration Release; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make test; make package; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then cpack; fi