dist: trusty
sudo: required
os:
  - linux
  - osx
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - rpm
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./build.linux.bsh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then ./build.xcode.bsh; fi
script:
  - gcc -v && g++ -v && cmake --version
  - cd build
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then xcodebuild -configuration Release; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make package; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then cpack; fi